
services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands-local-version-a2a:0.1
    container_name: openhands-instance-local-version
    environment:

      # Настройки для корректной работы A2A well-known uri.
      BACKEND_HOST: "192.168.145.147"
      BACKEND_PORT: "3000"

      # Настройки sandbox: используемый образ, дополнительные ENV и volumes
      SANDBOX_RUNTIME_CONTAINER_IMAGE: "node2.bdcl:5000/all-hands-ai/runtime:0.59-nikolaik-appfactory-components"

      # Для запуска с компонентами в моковом режиме
      # SANDBOX_RUNTIME_STARTUP_ENV_VARS: "{'APPFACTORY_MOCK': '1'}"

      # Для запуска с полноценной работой компонентов. Требуется развёрнутая инфраструктура.
      SANDBOX_RUNTIME_STARTUP_ENV_VARS: "\
      {'APPFACTORY_MOCK': '0', \
       'APPFACTORY_DLTOOL_SCORING_OPENAI_BASE_URL': 'http://d.dgx:58891/v1', \
       'APPFACTORY_DLTOOL_SCORING_OPENAI_API_KEY': 'REMOVED', \
       'APPFACTORY_DLTOOL_SCORING_WEB_DOC_AGENT_LLM_MODEL': '/models/e5-mistral-7b-instruct', \
       'APPFACTORY_RAG_GENERATOR_BASE_URL': 'http://d.dgx:34000/v1', \
       'APPFACTORY_RAG_GENERATOR_API_KEY': 'REMOVED', \
       'APPFACTORY_RAG_GENERATOR_MODEL_NAME': 'gpt-oss-120b', \
       'APPFACTORY_RAG_TOKENIZER_PATH': '/tokenizer', \
       'APPFACTORY_RAG_EMBEDDER_BASE_URL': 'http://d.dgx:58892/v1', \
       'APPFACTORY_RAG_EMBEDDER_API_KEY': 'REMOVED', \
       'APPFACTORY_RAG_EMBEDDER_MODEL_NAME': '/models/e5-mistral-7b-instruct', \
       'APPFACTORY_RAG_ELASTICSEARCH_URL': 'http://node13.bdcl:9200', \
       'APPFACTORY_RAG_ELASTICSEARCH_USER': 'elastic', \
       'APPFACTORY_RAG_ELASTICSEARCH_PASSWORD': 'REMOVED'}"

      # Образ sandbox должен содержать следующие директории:
      #  1. /appfactory_components (из AppFactory-components)
      #  2. /appfactory_docs (из AppFactory-components)
      #  3. /instructions (из AppFactory-a2a)
      #  4. /tokenizer
      # Иначе их необходимо вмонтировать с помощью volumes.
      SANDBOX_VOLUMES: "/path/to/dir/with/specs:/specs:ro"

      # Путь, в котором будут создаваться директории под volume отдельных рантаймов.
      # Каждая директория будет монтироваться только в свой рантайм. Таким образом получаем изолированные
      # workspace, и содержимое хранится вне контейнера.
      # Структура:
      # /path/to/dir/for/multiple/workspaces/
      #  └── <session_id>/
      #      ├── pyptoject.toml
      #      ├── main.py
      #      ├── code.py
      #      └── ...
      SANDBOX_ALL_WORKSPACES_DIR: "/path/to/dir/for/multiple/workspaces"

      LOG_ALL_EVENTS: "true"
      DEBUG: "true"

      LLM_API_KEY: "REMOVED"
      LLM_BASE_URL: "https://foundation-models.api.cloud.ru/v1"
      LLM_PROVIDER: "hosted_vllm"
      LLM_MODEL: "hosted_vllm/Qwen/Qwen3-Coder-480B-A35B-Instruct"
      LLM_TEMPERATURE: "0.7"
      LLM_TOP_P: "0.8"
      LLM_TOP_K: "20"
      LLM_COMPLETION_KWARGS: '{"repetition_penalty": 1.05}'

      # Настройка суммаризатора: сколько первых событий сохранять
      CONDENSER_KEEP_FIRST: "15"

      # Настройка суммаризатора: после скольки шагов выполнить суммаризацию.
      CONDENSER_MAX_SIZE: "400"

    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "a6k2.dgx:10.32.15.89"
      - "d.dgx:10.32.2.11"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      # Путь, где веб-инстанс будет хранить свои настройки. Перед запуском можно просто пустую директорию создать.
      - /path/to/web-instance/settings-dir:/.openhands:z

      # Аналогично, только для хранения данных о переписках, событиях и т.д.
      - /path/to/web-instance/workspace-dir:/opt/workspace_base:z

      # (Опционально) Путь до кода OpenHands. Полезно для разработки, чтобы не требовалось каждый раз пересобирать образ.
      - ./openhands:/app/openhands:z
      - ./microagents:/app/microagents:z
      - ./containers/app/entrypoint.sh:/app/entrypoint.sh:ro

  #  Нужен для компонента RAG в полноценном режиме работы
  elasticsearch:
    image: elasticsearch:8.15.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4G -Xmx4G
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=REMOVED
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
