
services:
  openhands-local-runtime:
    build:
      context: ./
      dockerfile: ./containers/app/local_runtime.dockerfile
    image: openhands-local-version-a2a:0.1
    container_name: openhands-instance-local-runtime
    environment:

      # Настройки для корректной работы A2A well-known uri.
      BACKEND_HOST: "10.32.15.14"
      BACKEND_PORT: "3001"

      # Устанавливаем local для запуска рантаймов
      RUNTIME: "local"
      DISABLE_VSCODE_PLUGIN: "true"

      # Для запуска с полноценной работой компонентов. Требуется развёрнутая инфраструктура.
      SANDBOX_RUNTIME_STARTUP_ENV_VARS: "\
      {'APPFACTORY_MOCK': '1', \
       'APPFACTORY_DLT_MOCK': '1', \
       'APPFACTORY_RAG_MOCK': '1', \
       'APPFACTORY_DLTOOL_SCORING_OPENAI_BASE_URL': 'http://d.dgx:58891/v1', \
       'APPFACTORY_DLTOOL_SCORING_OPENAI_API_KEY': 'token-abc123', \
       'APPFACTORY_DLTOOL_SCORING_WEB_DOC_AGENT_LLM_MODEL': '/models/e5-mistral-7b-instruct', \
       'APPFACTORY_RAG_GENERATOR_BASE_URL': 'http://d.dgx:34000/v1', \
       'APPFACTORY_RAG_GENERATOR_API_KEY': 'sk-teacher-key-123-litellm', \
       'APPFACTORY_RAG_GENERATOR_MODEL_NAME': 'gpt-oss-120b', \
       'APPFACTORY_RAG_TOKENIZER_PATH': '/tokenizer', \
       'APPFACTORY_RAG_EMBEDDER_BASE_URL': 'http://d.dgx:58892/v1', \
       'APPFACTORY_RAG_EMBEDDER_API_KEY': 'token-abc123', \
       'APPFACTORY_RAG_EMBEDDER_MODEL_NAME': '/models/e5-mistral-7b-instruct', \
       'APPFACTORY_RAG_ELASTICSEARCH_URL': 'http://10.32.15.14:9200', \
       'APPFACTORY_RAG_ELASTICSEARCH_USER': 'elastic', \
       'APPFACTORY_RAG_ELASTICSEARCH_PASSWORD': '123', \
       'APPFACTORY_LLM_API_KEY': 'sk-teacher-key-123-litellm', \
       'APPFACTORY_LLM_MODEL_NAME': 'gpt-oss-120b', \
       'APPFACTORY_LLM_BASE_URL': 'http://d.dgx:34000/v1', \
       'APPFACTORY_SEARCHTOOL_GENERATOR_BASE_URL': 'http://d.dgx:34000/v1', \
       'APPFACTORY_SEARCHTOOL_GENERATOR_API_KEY': 'sk-teacher-key-123-litellm', \
       'APPFACTORY_SEARCHTOOL_GENERATOR_MODEL_NAME': 'gpt-oss-120b', \
       'APPFACTORY_HH_URL': 'http://d.dgx:26676', \
       'APPFACTORY_SEARCHTOOL_REDIS_URL': 'redis://d.dgx:6479/1', \
       'REDIS_URL': 'redis://d.dgx:6479/1'}"

      # В контейнер должны быть вмонтированы следующие директории:
      #  1. /appfactory_components (из AppFactory-components)
      #  2. /appfactory_docs (из AppFactory-components)
      #  3. /instructions (из AppFactory-a2a)
      #  4. /tokenizer
      #  5. Также должна быть выполнена установка компонентов appfactory_components

      # Необходимо для корректной работы local runtime
      SANDBOX_VOLUMES: "/workspace:/workspace:z"

      DOCKER_HOST_ADDR: "10.32.15.14"

      LOG_ALL_EVENTS: "true"
      DEBUG: "true"

      LLM_API_KEY: "REMOVED"
      LLM_BASE_URL: "https://foundation-models.api.cloud.ru/v1"
      LLM_PROVIDER: "hosted_vllm"
      LLM_MODEL: "hosted_vllm/Qwen/Qwen3-Coder-480B-A35B-Instruct"
      LLM_TEMPERATURE: "0.7"
      LLM_TOP_P: "0.8"
      LLM_TOP_K: "20"
      LLM_COMPLETION_KWARGS: '{"repetition_penalty": 1.05}'

      # Настройка суммаризатора: сколько первых событий сохранять
      CONDENSER_KEEP_FIRST: "15"

      # Настройка суммаризатора: после скольки шагов выполнить суммаризацию.
      CONDENSER_MAX_SIZE: "400"

    ports:
      - "3001:3000"
      - "35000-35010:35000-35010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "a6k2.dgx:10.32.15.89"
      - "d.dgx:10.32.2.11"
    volumes:
      # Путь, где веб-инстанс будет хранить свои настройки. Перед запуском можно просто пустую директорию создать.
      - /data/hdd/wspace/OpenHands/local-runtime/settings-dir:/.openhands:z

      # Аналогично, только для хранения данных о переписках, событиях и т.д.
      - /data/hdd/wspace/OpenHands/local-runtime/workspace:/workspace:z

      # (Опционально) Путь до кода OpenHands. Полезно для разработки, чтобы не требовалось каждый раз пересобирать образ.
      - ./openhands:/app/openhands:z
      - ./microagents:/app/microagents:z
      - ./containers/app/entrypoint.sh:/app/entrypoint.sh:ro

  #  Нужен для компонента RAG в полноценном режиме работы
  elasticsearch:
    image: elasticsearch:8.15.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4G -Xmx4G
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=REMOVED
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
