
services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands-local-version-a2a:0.1
    container_name: openhands-instance-local-version
    environment:
      BACKEND_HOST: "192.168.145.147"
      BACKEND_PORT: "3000"
      LOG_ALL_EVENTS: "true"
      DEBUG: "true"

      LLM_API_KEY: "REMOVED"
      LLM_BASE_URL: "http://a6k2.dgx:34000"
      LLM_PROVIDER: "hosted_vllm"
      LLM_MODEL: "hosted_vllm/qwen3-32b"
      LLM_TEMPERATURE: "0.7"
      LLM_TOP_P: "0.8"
      LLM_TOP_K: "20"
      LLM_COMPLETION_KWARGS: '{"repetition_penalty": 1.05}'

      RUNTIME: "local"

      DOCKER_HOST_ADDR: "192.168.145.147"

      # Для того чтобы сессии работали в одной директории необходимо задать SANDBOX_VOLUMES с директорией /workspace.
      # Иначе создает временные директории для работы. В containers/app/Dockerfile должно быть WORKSPACE_BASE="/workspace"
      SANDBOX_VOLUMES: "/path/to/your/workspace:/workspace:rw"
    ports:
      - "3000:3000"
    # При runtime: local для работы vscode в web необходимо задать в файле openhands/runtime/impl/docker/docker_runtime.py диапазон VSCODE_PORT_RANGE
    # и открыть эти порты здесь
    #  - "35000-35010:35000-35010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "a6k2.dgx:10.32.15.89"
    volumes:
      - /path/to/web-instance/.openhands:/.openhands:z
      - /path/to/open-hands/openhands:/app/openhands:z
      - /path/to/open-hands/open-hands/microagents:/app/microagents:z
      - /path/to/open-hands/open-hands/containers/app/entrypoint.sh:/app/entrypoint.sh:ro
      - /path/to/your/workspace:/workspace:rw
