
services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands-local-version-a2a:0.1
    container_name: openhands-instance-local-version
    environment:
      BACKEND_HOST: "192.168.145.147"
      BACKEND_PORT: "3000"
      SANDBOX_RUNTIME_CONTAINER_IMAGE: "docker.all-hands.dev/all-hands-ai/runtime:0.59-nikolaik"
      LOG_ALL_EVENTS: "true"
      DEBUG: "true"
      LLM_API_KEY: "REMOVED"
      LLM_BASE_URL: "http://a6k2.dgx:34000"
      LLM_PROVIDER: "hosted_vllm"
      LLM_MODEL: "hosted_vllm/qwen3-32b"
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "a6k2.dgx:10.32.15.89"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/hgfs/Projects/MAS/OpenHands-Fork/.misc/web-instance/.openhands:/.openhands:z
      - /mnt/hgfs/Projects/MAS/OpenHands-Fork/openhands:/app/openhands:z
      - /mnt/hgfs/Projects/MAS/OpenHands-Fork/microagents:/app/microagents:z
      - /mnt/hgfs/Projects/MAS/OpenHands-Fork/containers/app/entrypoint.sh:/app/entrypoint.sh:ro
      - /mnt/hgfs/Projects/MAS/OpenHands-Fork/.misc/web-instance/workspace:/opt/workspace_base:z

